graphics_KernelMemory: Update i915 paths
This commit updates the paths used for i915 memory values and is a
follow up to the change submitted at [1]. Logging self.GKM.num_errors
is also replaced to address "Unhandled AttributeError:
'graphics_KernelMemory' object has no attribute 'GKM'".

Example failure message:
11/13 08:03:17.044 ERROR|    graphics_utils:1147| Unable to find any sysfs paths for field "memory"
TestFail: Failed: Detected 1 errors accessing graphics memory.

[1] https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1895010

BUG=None
TEST=Verify graphics_KernelMemory passes on a 5.x kernel
     - Build eve or nocturne with an updated kernel.
     - `test_that ${dut_ip} graphics_KernelMemory`

Change-Id: If95b29e514ad48dc53ee8d30a5c24a6fb2f5d83e
Signed-off-by: Edward Baker <edward.baker@intel.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1913635
Tested-by: Ilja H. Friedel <ihf@chromium.org>
Reviewed-by: Ilja H. Friedel <ihf@chromium.org>