autotest: Include last line of log in rpc server failure.
This change makes it so that failures to start an xmlrpc server will
report some of the actual failure message, rather than just saying
"Connection Refused" or "BadStatusLine('')" or an empty string.

This should help figure out the failure reasons from a dashboard,
without digging into the logs every time.

Example (wrapped on spaces):
  TestError: Failed to start XMLRPC server.
  socket.error: [Errno 104] Connection reset by peer: 'localhost:34065'.
  Log tail: 'bash: /usr/local/autotest/cros/faft/rpc_server.py:
      /usr/bin/python2: bad interpreter: Permission denied'

BUG=chromium:1054617
TEST=Run a test with DUT python chmod -x, or with rpc_server.py altered to have a syntax error.

Change-Id: Ifb5e35ede336030a3151cfdc68dff5c766a457e3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2105592
Tested-by: Dana Goyette <dgoyette@chromium.org>
Commit-Queue: Dana Goyette <dgoyette@chromium.org>
Reviewed-by: Greg Edelston <gredelston@google.com>